# Generated by Django 5.2 on 2025-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='action',
            field=models.CharField(default='login', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(upload_to='face_images/'),
        ),
    ]
